<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Lembaga;

class LembagaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // Kecamatan: Kota
            ['kategori_id' => 1, 'nama' => 'TPQ Al Hidayah', 'alamat' => 'Jl. Mawar No. 10', 'kelurahan' => 'Bawang', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08123456789', 'email' => 'tpq1@example.com', 'jumlah_guru' => 10, 'jumlah_siswa' => 120, 'sk' => 'SK-001', 'file_pendukung' => 'sk_tpq1.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Nur Ilahi', 'alamat' => 'Jl. Merdeka No. 45', 'kelurahan' => 'Kota', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08134567890', 'email' => 'tpq2@example.com', 'jumlah_guru' => 12, 'jumlah_siswa' => 150, 'sk' => 'SK-002', 'file_pendukung' => 'sk_tpq2.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Ar-Rahman', 'alamat' => 'Jl. Ahmad Yani No. 32', 'kelurahan' => 'Balowerjo', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08145678901', 'email' => 'tpq3@example.com', 'jumlah_guru' => 8, 'jumlah_siswa' => 95, 'sk' => 'SK-003', 'file_pendukung' => 'sk_tpq3.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ As-Salam', 'alamat' => 'Jl. Diponegoro No. 18', 'kelurahan' => 'Singonegaran', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08156789012', 'email' => 'tpq4@example.com', 'jumlah_guru' => 11, 'jumlah_siswa' => 135, 'sk' => 'SK-004', 'file_pendukung' => 'sk_tpq4.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Al-Quran', 'alamat' => 'Jl. Gatot Subroto No. 25', 'kelurahan' => 'Semampir', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08167890123', 'email' => 'tpq5@example.com', 'jumlah_guru' => 9, 'jumlah_siswa' => 110, 'sk' => 'SK-005', 'file_pendukung' => 'sk_tpq5.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Baitul Ilm', 'alamat' => 'Jl. Slamet Riyadi No. 55', 'kelurahan' => 'Tinalan', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08178901234', 'email' => 'tpq6@example.com', 'jumlah_guru' => 13, 'jumlah_siswa' => 160, 'sk' => 'SK-006', 'file_pendukung' => 'sk_tpq6.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Bin Baz', 'alamat' => 'Jl. Jenderal Sudirman No. 75', 'kelurahan' => 'Jagalan', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08189012345', 'email' => 'tpq7@example.com', 'jumlah_guru' => 10, 'jumlah_siswa' => 125, 'sk' => 'SK-007', 'file_pendukung' => 'sk_tpq7.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Darul Hana', 'alamat' => 'Jl. Veteran No. 40', 'kelurahan' => 'Bawang', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08190123456', 'email' => 'tpq8@example.com', 'jumlah_guru' => 11, 'jumlah_siswa' => 140, 'sk' => 'SK-008', 'file_pendukung' => 'sk_tpq8.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Hafizh Hana', 'alamat' => 'Jl. Letnan Jendral No. 62', 'kelurahan' => 'Kota', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08201234567', 'email' => 'tpq9@example.com', 'jumlah_guru' => 12, 'jumlah_siswa' => 155, 'sk' => 'SK-009', 'file_pendukung' => 'sk_tpq9.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Anak Sholeh', 'alamat' => 'Jl. Rajawali No. 28', 'kelurahan' => 'Balowerjo', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08212345678', 'email' => 'tpq10@example.com', 'jumlah_guru' => 9, 'jumlah_siswa' => 115, 'sk' => 'SK-010', 'file_pendukung' => 'sk_tpq10.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Cerdas Mulia', 'alamat' => 'Jl. Teluk No. 35', 'kelurahan' => 'Singonegaran', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08223456789', 'email' => 'tpq11@example.com', 'jumlah_guru' => 10, 'jumlah_siswa' => 130, 'sk' => 'SK-011', 'file_pendukung' => 'sk_tpq11.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Fatih Ilm', 'alamat' => 'Jl. Basuki No. 52', 'kelurahan' => 'Semampir', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08234567890', 'email' => 'tpq12@example.com', 'jumlah_guru' => 11, 'jumlah_siswa' => 145, 'sk' => 'SK-012', 'file_pendukung' => 'sk_tpq12.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Hikmah Abadi', 'alamat' => 'Jl. Sukarno No. 42', 'kelurahan' => 'Tinalan', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08245678901', 'email' => 'tpq13@example.com', 'jumlah_guru' => 13, 'jumlah_siswa' => 170, 'sk' => 'SK-013', 'file_pendukung' => 'sk_tpq13.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Ilmu Pengetahuan', 'alamat' => 'Jl. Untung Suropati No. 68', 'kelurahan' => 'Jagalan', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08256789012', 'email' => 'tpq14@example.com', 'jumlah_guru' => 12, 'jumlah_siswa' => 158, 'sk' => 'SK-014', 'file_pendukung' => 'sk_tpq14.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Jaya Amira', 'alamat' => 'Jl. Pattimura No. 15', 'kelurahan' => 'Kota', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08267890123', 'email' => 'tpq15@example.com', 'jumlah_guru' => 10, 'jumlah_siswa' => 122, 'sk' => 'SK-015', 'file_pendukung' => 'sk_tpq15.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Karunia Hati', 'alamat' => 'Jl. Cemara No. 33', 'kelurahan' => 'Balowerjo', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08278901234', 'email' => 'tpq16@example.com', 'jumlah_guru' => 11, 'jumlah_siswa' => 138, 'sk' => 'SK-016', 'file_pendukung' => 'sk_tpq16.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Lancar Belajar', 'alamat' => 'Jl. Pandanaran No. 50', 'kelurahan' => 'Singonegaran', 'kecamatan' => 'Kota', 'kabkota' => 'Kota Kediri', 'telp' => '08289012345', 'email' => 'tpq17@example.com', 'jumlah_guru' => 9, 'jumlah_siswa' => 108, 'sk' => 'SK-017', 'file_pendukung' => 'sk_tpq17.pdf'],
            
            // Kecamatan: Mojoroto
            ['kategori_id' => 1, 'nama' => 'TPQ Mujahidin', 'alamat' => 'Jl. Sumatra No. 22', 'kelurahan' => 'Mojoroto', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08290123456', 'email' => 'tpq18@example.com', 'jumlah_guru' => 12, 'jumlah_siswa' => 148, 'sk' => 'SK-018', 'file_pendukung' => 'sk_tpq18.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Mulia Insani', 'alamat' => 'Jl. Jawa No. 38', 'kelurahan' => 'Batur', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08301234567', 'email' => 'tpq19@example.com', 'jumlah_guru' => 10, 'jumlah_siswa' => 128, 'sk' => 'SK-019', 'file_pendukung' => 'sk_tpq19.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Nada Indah', 'alamat' => 'Jl. Kalimantan No. 45', 'kelurahan' => 'Tosaren', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08312345678', 'email' => 'tpq20@example.com', 'jumlah_guru' => 11, 'jumlah_siswa' => 142, 'sk' => 'SK-020', 'file_pendukung' => 'sk_tpq20.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Nur Amin', 'alamat' => 'Jl. Sulawesi No. 20', 'kelurahan' => 'Ploso', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08323456789', 'email' => 'tpq21@example.com', 'jumlah_guru' => 13, 'jumlah_siswa' => 165, 'sk' => 'SK-021', 'file_pendukung' => 'sk_tpq21.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Optimal Hana', 'alamat' => 'Jl. Papua No. 58', 'kelurahan' => 'Kemiri', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08334567890', 'email' => 'tpq22@example.com', 'jumlah_guru' => 10, 'jumlah_siswa' => 118, 'sk' => 'SK-022', 'file_pendukung' => 'sk_tpq22.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Pesona Ilmu', 'alamat' => 'Jl. Riau No. 65', 'kelurahan' => 'Mojoroto', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08345678901', 'email' => 'tpq23@example.com', 'jumlah_guru' => 12, 'jumlah_siswa' => 152, 'sk' => 'SK-023', 'file_pendukung' => 'sk_tpq23.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Qibla Ilm', 'alamat' => 'Jl. Bengkulu No. 30', 'kelurahan' => 'Batur', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08356789012', 'email' => 'tpq24@example.com', 'jumlah_guru' => 11, 'jumlah_siswa' => 135, 'sk' => 'SK-024', 'file_pendukung' => 'sk_tpq24.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Ruhul Amin', 'alamat' => 'Jl. Aceh No. 48', 'kelurahan' => 'Tosaren', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08367890123', 'email' => 'tpq25@example.com', 'jumlah_guru' => 9, 'jumlah_siswa' => 105, 'sk' => 'SK-025', 'file_pendukung' => 'sk_tpq25.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Sinar Ilmu', 'alamat' => 'Jl. Jambi No. 70', 'kelurahan' => 'Ploso', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08378901234', 'email' => 'tpq26@example.com', 'jumlah_guru' => 14, 'jumlah_siswa' => 175, 'sk' => 'SK-026', 'file_pendukung' => 'sk_tpq26.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Tauhid Jaya', 'alamat' => 'Jl. Bali No. 25', 'kelurahan' => 'Kemiri', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08389012345', 'email' => 'tpq27@example.com', 'jumlah_guru' => 10, 'jumlah_siswa' => 123, 'sk' => 'SK-027', 'file_pendukung' => 'sk_tpq27.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Ulul Albab', 'alamat' => 'Jl. Nusa No. 55', 'kelurahan' => 'Mojoroto', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08390123456', 'email' => 'tpq28@example.com', 'jumlah_guru' => 12, 'jumlah_siswa' => 147, 'sk' => 'SK-028', 'file_pendukung' => 'sk_tpq28.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Visi Mulia', 'alamat' => 'Jl. Timor No. 40', 'kelurahan' => 'Batur', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08401234567', 'email' => 'tpq29@example.com', 'jumlah_guru' => 11, 'jumlah_siswa' => 136, 'sk' => 'SK-029', 'file_pendukung' => 'sk_tpq29.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Wicara Qur\'an', 'alamat' => 'Jl. Maluku No. 62', 'kelurahan' => 'Tosaren', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08412345678', 'email' => 'tpq30@example.com', 'jumlah_guru' => 13, 'jumlah_siswa' => 162, 'sk' => 'SK-030', 'file_pendukung' => 'sk_tpq30.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Xanth Belajar', 'alamat' => 'Jl. Sunda No. 35', 'kelurahan' => 'Ploso', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08423456789', 'email' => 'tpq31@example.com', 'jumlah_guru' => 10, 'jumlah_siswa' => 127, 'sk' => 'SK-031', 'file_pendukung' => 'sk_tpq31.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Yakin Qur\'an', 'alamat' => 'Jl. Flores No. 18', 'kelurahan' => 'Kemiri', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08434567890', 'email' => 'tpq32@example.com', 'jumlah_guru' => 9, 'jumlah_siswa' => 112, 'sk' => 'SK-032', 'file_pendukung' => 'sk_tpq32.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Zahra Cantik', 'alamat' => 'Jl. Komodo No. 75', 'kelurahan' => 'Mojoroto', 'kecamatan' => 'Mojoroto', 'kabkota' => 'Kota Kediri', 'telp' => '08445678901', 'email' => 'tpq33@example.com', 'jumlah_guru' => 14, 'jumlah_siswa' => 180, 'sk' => 'SK-033', 'file_pendukung' => 'sk_tpq33.pdf'],

            // Kecamatan: Pesantren
            ['kategori_id' => 1, 'nama' => 'TPQ Pesantren Murni', 'alamat' => 'Jl. Kyai No. 10', 'kelurahan' => 'Pesantren', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08456789012', 'email' => 'tpq34@example.com', 'jumlah_guru' => 15, 'jumlah_siswa' => 200, 'sk' => 'SK-034', 'file_pendukung' => 'sk_tpq34.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Abidah Ilmu', 'alamat' => 'Jl. Syech No. 22', 'kelurahan' => 'Cakru', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08467890123', 'email' => 'tpq35@example.com', 'jumlah_guru' => 11, 'jumlah_siswa' => 140, 'sk' => 'SK-035', 'file_pendukung' => 'sk_tpq35.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Bayan Insani', 'alamat' => 'Jl. Haji No. 32', 'kelurahan' => 'Bancar', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08478901234', 'email' => 'tpq36@example.com', 'jumlah_guru' => 12, 'jumlah_siswa' => 153, 'sk' => 'SK-036', 'file_pendukung' => 'sk_tpq36.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Cahaya Islam', 'alamat' => 'Jl. Pesantren No. 45', 'kelurahan' => 'Pesantren', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08489012345', 'email' => 'tpq37@example.com', 'jumlah_guru' => 13, 'jumlah_siswa' => 167, 'sk' => 'SK-037', 'file_pendukung' => 'sk_tpq37.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Daulat Hana', 'alamat' => 'Jl. Santri No. 55', 'kelurahan' => 'Cakru', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08490123456', 'email' => 'tpq38@example.com', 'jumlah_guru' => 10, 'jumlah_siswa' => 130, 'sk' => 'SK-038', 'file_pendukung' => 'sk_tpq38.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Elmyna Jaya', 'alamat' => 'Jl. Pelajar No. 18', 'kelurahan' => 'Bancar', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08501234567', 'email' => 'tpq39@example.com', 'jumlah_guru' => 11, 'jumlah_siswa' => 144, 'sk' => 'SK-039', 'file_pendukung' => 'sk_tpq39.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Fabiyah Ilm', 'alamat' => 'Jl. Mandiri No. 65', 'kelurahan' => 'Pesantren', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08512345678', 'email' => 'tpq40@example.com', 'jumlah_guru' => 14, 'jumlah_siswa' => 178, 'sk' => 'SK-040', 'file_pendukung' => 'sk_tpq40.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Gaharu Mulia', 'alamat' => 'Jl. Ilmu No. 28', 'kelurahan' => 'Cakru', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08523456789', 'email' => 'tpq41@example.com', 'jumlah_guru' => 12, 'jumlah_siswa' => 156, 'sk' => 'SK-041', 'file_pendukung' => 'sk_tpq41.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Harmoni Qur\'an', 'alamat' => 'Jl. Adab No. 42', 'kelurahan' => 'Bancar', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08534567890', 'email' => 'tpq42@example.com', 'jumlah_guru' => 10, 'jumlah_siswa' => 125, 'sk' => 'SK-042', 'file_pendukung' => 'sk_tpq42.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Insan Mulia', 'alamat' => 'Jl. Taqwa No. 70', 'kelurahan' => 'Pesantren', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08545678901', 'email' => 'tpq43@example.com', 'jumlah_guru' => 13, 'jumlah_siswa' => 169, 'sk' => 'SK-043', 'file_pendukung' => 'sk_tpq43.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Jayyid Insani', 'alamat' => 'Jl. Iffah No. 35', 'kelurahan' => 'Cakru', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08556789012', 'email' => 'tpq44@example.com', 'jumlah_guru' => 11, 'jumlah_siswa' => 139, 'sk' => 'SK-044', 'file_pendukung' => 'sk_tpq44.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Khotibah Qur\'an', 'alamat' => 'Jl. Hikmah No. 50', 'kelurahan' => 'Bancar', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08567890123', 'email' => 'tpq45@example.com', 'jumlah_guru' => 12, 'jumlah_siswa' => 151, 'sk' => 'SK-045', 'file_pendukung' => 'sk_tpq45.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Luthfi Ilm', 'alamat' => 'Jl. Qolbu No. 15', 'kelurahan' => 'Pesantren', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08578901234', 'email' => 'tpq46@example.com', 'jumlah_guru' => 10, 'jumlah_siswa' => 120, 'sk' => 'SK-046', 'file_pendukung' => 'sk_tpq46.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Mutiara Ilmu', 'alamat' => 'Jl. Rasa No. 60', 'kelurahan' => 'Cakru', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08589012345', 'email' => 'tpq47@example.com', 'jumlah_guru' => 14, 'jumlah_siswa' => 182, 'sk' => 'SK-047', 'file_pendukung' => 'sk_tpq47.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Nursal Qur\'an', 'alamat' => 'Jl. Halal No. 25', 'kelurahan' => 'Bancar', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08590123456', 'email' => 'tpq48@example.com', 'jumlah_guru' => 11, 'jumlah_siswa' => 133, 'sk' => 'SK-048', 'file_pendukung' => 'sk_tpq48.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Oscara Ilm', 'alamat' => 'Jl. Haram No. 38', 'kelurahan' => 'Pesantren', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08601234567', 'email' => 'tpq49@example.com', 'jumlah_guru' => 12, 'jumlah_siswa' => 146, 'sk' => 'SK-049', 'file_pendukung' => 'sk_tpq49.pdf'],
            ['kategori_id' => 1, 'nama' => 'TPQ Pemimpin Hati', 'alamat' => 'Jl. Siddiq No. 72', 'kelurahan' => 'Cakru', 'kecamatan' => 'Pesantren', 'kabkota' => 'Kota Kediri', 'telp' => '08612345678', 'email' => 'tpq50@example.com', 'jumlah_guru' => 13, 'jumlah_siswa' => 171, 'sk' => 'SK-050', 'file_pendukung' => 'sk_tpq50.pdf'],
        ];

        foreach ($data as $item) {
            Lembaga::create($item);
        }
    }
}
